### PR TITLE
Conditionally Selection gadget for R1CS.

### PR DESCRIPTION
**Pull request by CPerezz**

### CODE REVIEW

**Comment by CPerezz** [comment]
I was mistaken on the way I initially understood this gadget functionallity.

If the bits of the Sk were not commited, we would be able to to apply conditions over them since we would know the value of each bit of the Sk and so we would have been able to conditionally operate (Add or Double) according to it.

In this case, the Sk bits are committed. This forces us to work with the blinded values. Add constrains to check if the bit is one or zero is not possible since they will be evaluated with the whole circuit and we cannot apply conditions there.

## Solution
The idea then should be using[ Left to right binary scalar mul algorithm](https://github.com/dusk-network/dusk-zerocaf/blob/436d76ac77e4babb089f849d7e02c7d788529057/src/edwards.rs#L122).

We would perform both the double and the addition on each round but we will conditionally assing `Q` to be the Identity point if the bit is `0` in the statement `Q = &Q + &point` and we will use the correct `Q` coordinates when we get `1` as bit.

This is not the most optimal way of performing the scalar mul, but at least we will be able to have a working implementation. We can always optimise it later.

**Comment by CPerezz** [comment]
The `prove` and `verify` functions added in this PR are only used for testing purposes doing a conditional addition operation inside R1CS.

The only important piece of code added is the `conditional_selection_gadget`

**Review by vlopes11 — APPROVED** [review]
All seems fine! Good job!

**Comment by CPerezz** [comment]
This was implemented within the refactor of `SonnyRistrettoPointGadget` in #13 and was concretely implemented in aaa96d3 . So this PR is outdated and so, it can be closed.

**Pull request closed without merging**
